"""add notification preferences to users

Revision ID: 84f6fcc3da48
Revises: fa06dc1003d1
Create Date: 2026-07-11 20:34:04.824686

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f6fcc3da48'
down_revision: str | None = 'fa06dc1003d1'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # server_default backfills existing rows so the NOT NULL constraint can be
    # applied in place; matches the ORM model's Python-side defaults.
    op.add_column('users', sa.Column('notify_document_processing', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('notify_weekly_summary', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('notify_product_updates', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_product_updates')
    op.drop_column('users', 'notify_weekly_summary')
    op.drop_column('users', 'notify_document_processing')
    # ### end Alembic commands ###
